### ISSUE TITLE
Category Issue on Item Form

### ISSUE THREAD

**Issue by noonnightcoder** [noonnightcoder/peedor-app#2]
The category just created inline on Item Form does not appear in as parent selection after we click "Create New" button again.
<img width="356" alt="screen shot 2018-05-26 at 6 27 48 am" src="https://user-images.githubusercontent.com/5521789/40569779-a2632464-60ae-11e8-944b-72f076aa0932.png">
<img width="603" alt="screen shot 2018-05-26 at 6 30 25 am" src="https://user-images.githubusercontent.com/5521789/40569781-a32b30c6-60ae-11e8-944b-084bf5c7ea82.png">

**Comment by snak-evil** [comment]
fixed By B. Lux
